
export const products = [
  {
    id: 1,
    name: 'Elegant Velvet Sofa',
    images: [
      { id: 1, url: 'https://picsum.photos/seed/p1-1/800/600' },
      { id: 2, url: 'https://picsum.photos/seed/p1-2/800/600' },
      { id: 3, url: 'https://picsum.photos/seed/p1-3/800/600' },
    ],
    description: 'A luxurious and comfortable sofa, upholstered in premium velvet. Its timeless design and plush cushions make it the perfect centerpiece for any modern living room. Built with a sturdy hardwood frame for lasting durability.',
    price: 899.99,
    discount: 10,
    stock: 120,
    category: 'Living Room',
    rating: 4.8,
    reviews: 25,
    dimensions: '88" W x 35" D x 32" H',
    material: 'Velvet, Hardwood',
    color: 'Royal Blue',
    createdAt: '2023-01-15T10:30:00Z',
    updatedAt: '2023-05-20T14:00:00Z',
  },
  {
    id: 2,
    name: 'Mid-Century Modern Desk',
    images: [
      { id: 1, url: 'https://picsum.photos/seed/p2-1/800/600' },
      { id: 2, url: 'https://picsum.photos/seed/p2-2/800/600' },
    ],
    description: 'Bring a touch of classic style to your workspace with this mid-century modern desk. Featuring clean lines, tapered legs, and ample storage with two drawers, it combines functionality with iconic design.',
    price: 349.99,
    discount: 0,
    stock: 75,
    category: 'Office',
    rating: 4.7,
    reviews: 42,
    dimensions: '48" W x 24" D x 30" H',
    material: 'Solid Walnut Wood',
    color: 'Walnut',
    createdAt: '2023-02-10T11:00:00Z',
    updatedAt: '2023-04-22T09:15:00Z',
  },
  {
    id: 3,
    name: 'Rustic Farmhouse Table',
    images: [
      { id: 1, url: 'https://picsum.photos/seed/p3-1/800/600' },
    ],
    description: 'Gather your family around this beautiful rustic farmhouse dining table. Made from reclaimed pine, its character-rich surface tells a story. Seats up to six people comfortably.',
    price: 650.0,
    discount: 15,
    stock: 0,
    category: 'Dining',
    rating: 4.9,
    reviews: 58,
    dimensions: '72" L x 36" W x 30" H',
    material: 'Reclaimed Pine',
    color: 'Natural Brown',
    createdAt: '2023-03-05T08:00:00Z',
    updatedAt: '2023-06-01T12:00:00Z',
  },
  {
    id: 4,
    name: 'Upholstered Queen Bed',
    images: [
      { id: 1, url: 'https://picsum.photos/seed/p4-1/800/600' },
      { id: 2, url: 'https://picsum.photos/seed/p4-2/800/600' },
      { id: 3, url: 'https://picsum.photos/seed/p4-3/800/600' },
    ],
    description: 'Create a serene and stylish bedroom with this upholstered queen bed. The soft, padded headboard is perfect for leaning against while reading, and the neutral fabric complements any decor.',
    price: 599.0,
    discount: 0,
    stock: 90,
    category: 'Bedroom',
    rating: 4.6,
    reviews: 33,
    dimensions: '64" W x 85" L x 45" H',
    material: 'Linen Blend Fabric, Wood',
    color: 'Light Gray',
    createdAt: '2023-04-12T16:45:00Z',
    updatedAt: '2023-05-30T11:20:00Z',
  },
  {
    id: 5,
    name: 'Leather Recliner Chair',
    images: [
      { id: 1, url: 'https://picsum.photos/seed/p5-1/800/600' },
      { id: 2, url: 'https://picsum.photos/seed/p5-2/800/600' },
    ],
    description: 'Unwind in ultimate comfort with this luxurious leather recliner. Featuring plush padding and a smooth reclining mechanism, it\'s the perfect spot for relaxation after a long day.',
    price: 720.0,
    discount: 5,
    stock: 65,
    category: 'Living Room',
    rating: 4.8,
    reviews: 28,
    dimensions: '38" W x 40" D x 42" H',
    material: 'Top-Grain Leather',
    color: 'Cognac',
    createdAt: '2023-01-20T13:10:00Z',
    updatedAt: '2023-05-18T18:00:00Z',
  },
  {
    id: 6,
    name: 'Industrial Bookshelf',
    images: [
      { id: 1, url: 'https://picsum.photos/seed/p6-1/800/600' },
    ],
    description: 'Showcase your books and decor with this industrial-style bookshelf. The combination of metal and wood creates a chic, urban look that fits well in any modern office or living space.',
    price: 280.0,
    discount: 0,
    stock: 30,
    category: 'Office',
    rating: 4.5,
    reviews: 19,
    dimensions: '36" W x 12" D x 72" H',
    material: 'Steel, MDF',
    color: 'Black/Oak',
    createdAt: '2023-02-25T09:00:00Z',
    updatedAt: '2023-04-15T14:30:00Z',
  },
  {
    id: 7,
    name: 'Bohemian Style Armchair',
    images: [
      { id: 1, url: 'https://picsum.photos/seed/p7-1/800/600' },
      { id: 2, url: 'https://picsum.photos/seed/p7-2/800/600' },
    ],
    description: 'Add a touch of boho charm to your home with this stylish armchair. Its natural rattan frame and comfortable cushion make it an inviting and eye-catching accent piece.',
    price: 420.0,
    discount: 20,
    stock: 25,
    category: 'Living Room',
    rating: 4.9,
    reviews: 45,
    dimensions: '28" W x 30" D x 34" H',
    material: 'Rattan, Cotton',
    color: 'Natural/White',
    createdAt: '2023-03-18T11:25:00Z',
    updatedAt: '2023-06-02T10:10:00Z',
  },
  {
    id: 8,
    name: 'Minimalist Coffee Table',
    images: [
      { id: 1, url: 'https://picsum.photos/seed/p8-1/800/600' },
    ],
    description: 'A sleek and simple coffee table that embodies minimalist design. Its clean lines and neutral color palette allow it to blend seamlessly into any living room setup.',
    price: 199.99,
    discount: 0,
    stock: 150,
    category: 'Living Room',
    rating: 4.7,
    reviews: 36,
    dimensions: '40" L x 20" W x 16" H',
    material: 'Lacquered MDF',
    color: 'White',
    createdAt: '2023-05-01T18:00:00Z',
    updatedAt: '2023-05-25T15:00:00Z',
  },
];
