
export const products = [
  {
    id: 1,
    name: 'Elegant Velvet Sofa',
    imageUrl: 'https://picsum.photos/seed/p1/600/400',
    price: 899.99,
    stock: 120,
    category: 'Living Room',
    rating: 4.8,
  },
  {
    id: 2,
    name: 'Mid-Century Modern Desk',
    imageUrl: 'https://picsum.photos/seed/p2/600/400',
    price: 349.99,
    stock: 75,
    category: 'Office',
    rating: 4.7,
  },
  {
    id: 3,
    name: 'Rustic Farmhouse Table',
    imageUrl: 'https://picsum.photos/seed/p3/600/400',
    price: 650.0,
    stock: 0,
    category: 'Dining',
    rating: 4.9,
  },
  {
    id: 4,
    name: 'Upholstered Queen Bed',
    imageUrl: 'https://picsum.photos/seed/p4/600/400',
    price: 599.0,
    stock: 90,
    category: 'Bedroom',
    rating: 4.6,
  },
  {
    id: 5,
    name: 'Leather Recliner Chair',
    imageUrl: 'https://picsum.photos/seed/p5/600/400',
    price: 720.0,
    stock: 65,
    category: 'Living Room',
    rating: 4.8,
  },
  {
    id: 6,
    name: 'Industrial Bookshelf',
    imageUrl: 'https://picsum.photos/seed/p6/600/400',
    price: 280.0,
    stock: 30,
    category: 'Office',
    rating: 4.5,
  },
    {
    id: 7,
    name: 'Bohemian Style Armchair',
    imageUrl: 'https://picsum.photos/seed/p7/600/400',
    price: 420.0,
    stock: 25,
    category: 'Living Room',
    rating: 4.9,
  },
  {
    id: 8,
    name: 'Minimalist Coffee Table',
    imageUrl: 'https://picsum.photos/seed/p8/600/400',
    price: 199.99,
    stock: 150,
    category: 'Living Room',
    rating: 4.7,
  },
];
